config/routes.rb
Rails.application.routes.draw do

    # Root 'home' controller
    root 'welcome#home'

    # Users controller
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'

    # Nested Resource Routes
    resources :users, :only => [:show] do
      resources :trips, :only => [:new, :create, :show, :index, :edit, :update]
    end

    # Items Routes
    get 'items/create'

    # Sessions Controller
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    #Sessions Omniauthable
    get '/auth/:provider/callback', to: 'sessions#create'

    #Trip routes
    resources :trips


    get 'trips/:id/next', to: 'trips#next'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :packing_lists
  has_one :trip, through: :packing_lists
end

app/models/packing_list.rb
class PackingList < ApplicationRecord
  belongs_to :trip
  belongs_to :item
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :packing_lists
  has_many :items, through: :packing_lists, :dependent => :destroy

  validates :name, presence: true
  validates :duration, presence: true
  validates :start_date, presence: true
  accepts_nested_attributes_for :items, reject_if: proc {|attributes| attributes['name'].blank?}, allow_destroy: true

  def items_attributes=(item_attributes)
    item_attributes.values.each do |item_attribute|
      if !item_attribute.empty?
        new_item = Item.find_or_create_by(item_attribute)
        self.items << new_item
      end
    end
  end

  STATUS = {
    :incomplete => 0,
    :complete => 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end

  def next_id
      trip = Trip.where("id > ?", id).first
      if trip
          trip.id
      else
          Trip.first.id
      end
  end


 #Active Record Model Class Methods

   def self.complete
     where("status = '1'")
   end

   def self.incomplete
     where("status = '0'")
   end

   def self.by_name(trip_name)
     where("name LIKE ?", "%#{trip_name}%")
   end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips

  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_for_user, only: [:new, :create]

  def new
  end

  def create
    #Log in via Github Flow
    if auth_hash = request.env["omniauth.auth"]

      oauth_email = request.env["omniauth.auth"]["info"]["email"]
      if user = User.find_by(:email => oauth_email)
        log_in user
        redirect_to user
      else
        user = User.new(:email => oauth_email, :password => SecureRandom.hex)
        if user.save
          log_in user
          redirect_to user
        else
          flash.now[:notice] = 'Invalid email/password combination'
        end
      end
    else
    # Normal Login Flow
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user
      else
        flash.now[:notice] = 'Invalid email/password combination'
        render 'new'
      end
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end

  private

  def check_for_user
    if current_user
      redirect_to user_path current_user.id
    end
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :set_trip, only: [:show, :edit, :update]

    def index
        @trips = Trip.all.where(user: current_user)
        respond_to do |f|
            f.html {render :index}
            f.json { render json: @trips}
        end
    end

    def show
        @item = @trip.items.build

        respond_to do |format|
            format.html { render :show }
            format.json { render json: @trip}
        end
    end

    def next
        next_id = Trip.find(params[:id]).next_id
        @trip = Trip.find(next_id)
        render json: @trip
    end

    def new
        @trip = Trip.new
    end

    def create
        @trip = Trip.new(trip_params)
        @trip.user = current_user

        if @trip.save
            redirect_to trip_path @trip.id
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @trip.update(trip_params)
            render json: @trip
        end
    end

  def destroy
    @trip = Trip.find(params[:id]).destroy
    redirect_to trips_url
  end


  private

    def set_trip
        @trip = Trip.find(params[:id])
    end

    def trip_params
        params.require(:trip).permit(:name, :duration, :start_date, :status, :item_ids => [], items_attributes: [:name])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show]
    before_action :check_for_user, only: [:new]

    def show
    end

    def new
      @user = User.new
    end

    def create
      @user = User.create(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        render 'new'
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def check_for_user
      if current_user
        redirect_to user_path current_user.id
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    if current_user
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !!current_user
  end

  def on_login_page?
    path = request.env['PATH_INFO']
    return path['/login'] || path['/signup']
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html class="no-js" lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
    <title>Pack it!</title>
</head>

<body>
    <div class="wrapper">
        <div class="header">
            <div class="logo">
            </div>
            <div class="userInfo">
            <% if logged_in? %>
                <i><h4>@<%= link_to current_user.name, user_path(current_user.id) %></h4></i>
            <% end %>
            </div>
        </div>

         <%= yield %>

        <footer class="branding">
        <div class="links">
            <% if logged_in? %>
                <%= link_to 'Back', 'javascript:history.back()' %> | <%= link_to "Log out", logout_path, method: :delete %>
            <% end %>
        </div>

        <small>&copy; 2018 <strong>Pack-it!</strong></small>
        </footer>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <br>
    <div class="field">
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

app/views/shared/_trip_error_messages.html.erb
<% if @trip.errors.any? %>
    <div>
      <h3>There were some errors:</h3>

      <div class="field">
        <ul>
          <% @trip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>

    </div>
  <% end %>

app/views/trips/_form.html.erb
<%= form_for ([current_user, trip]) do |f| %>
    <%= render 'shared/trip_error_messages' %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="field">
      <%= f.label :duration %><br>
      <%= f.text_field :duration %>
    </div>
    <br>
    <div class="field">
      <%= f.label :start_date %><br>
      <%= f.date_field :start_date %>
    </div>
    <br>
    <br>
    <div class="field">
      <h3>Packing List</h3>
      <h5><i>Add Items to List</i></h5>
      <% 5.times.each do %>
        <%= f.fields_for :items, trip.items.build do |trip_fields| %>
          <%= trip_fields.text_field :name %><br>
        <% end %>
      <% end %>
    </div>
    <%= f.submit %>
<% end %>

app/views/trips/edit.html.erb
<h2>Edit Trip</h2>

<%= render partial: "form", locals: {trip: @trip} %>

app/views/trips/index.html.erb
<h2>Trips</h2>

<% if @trips.count > 0 %>
  <% @trips.each do |trip| %>
    <ul>
      <div class="trip">
        <li>
          <%= link_to trip.name, user_trip_path(current_user.id, trip.id) %>
        </li>
      </div>
    </ul>
  <% end %>
<% else %>
  <div class="">
    <%= link_to "Create Trip", new_trip_path %>
  </div>
<% end %>

<br>
<br>

<!-- <div>
  <h3>View by:</h3>
    <%= form_tag("/trips", method: "get") do %>
      <%= select_tag "status", options_for_select(["Past", "Upcoming"]), include_blank: true %>
    <%= submit_tag "Filter" %>
    <% end %>
</div>

<div>
  <h3>Find by Name:</h3>
  <%= form_tag("/trips", method: "get") do %>
    <%= select_tag "name", options_from_collection_for_select(Trip.where(user: current_user), "name", "name"), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div> -->

app/views/trips/new.html.erb
<h2>Create a Trip</h2>

<%= render partial: "form", locals: {trip: @trip} %>

app/views/trips/show.html.erb
<div class="links">
    <a href="/trips/<%= @trip.next_id %>" class="js-next">Next Trip</a>
</div>

<h1 class="tripName"><%= @trip.name %></h1>
<h3 class="tripDuration"><%= @trip.duration %></h3>
<h3 class="tripStartdate"><%= @trip.start_date %></p>

<div class="">
  <%= link_to 'Edit', edit_trip_path(@trip) %> | <%= link_to "Delete", @trip, method: :delete %>
</div>

<br>

<h2>Packing List</h2>

<ul class="tripItems">
    <% if @trip.items.count > 0 %>
        <% @trip.items.each do |item| %>
          <li><%= item.name %> </li>
        <% end %>
     <% else %>
         <li>Add Items to List</li>
    <% end %>
</ul>

<br>

<%= form_for @trip do |f| %>
      <% 1.times.each do %>
        <%= f.fields_for :items, @trip.items.build do |trip_fields| %>
          <%= trip_fields.text_field :name %><br>
        <% end %>
      <% end %>
    <%= f.submit 'Add Item', data: {disable_with: false} %>
<% end %>

<!-- <br>

<div class="">
  <%= form_for ([current_user, @trip]) do |f| %>
    <h4><%= f.label "Is this Trip Complete?" %></h4>
    <%= f.check_box :status, options = {:onChange => "javascript: this.form.submit();"}, checked_value = "1", unchecked_value = "0" %>
  <% end %>
</div> -->

app/views/users/new.html.erb
<h2>Sign Up</h2>


<%= form_for(@user, url: signup_path) do |f| %>

    <%= render 'shared/error_messages' %>
    <br>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <br>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <br>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <br>

    <%= f.submit "Create Account"%>
<% end %>

app/views/users/show.html.erb
<h2>Hi @<%= current_user.name %>!</h2>

<div id="trips-container">

</div>

<br>

<div class="links">
  <div class="">
    <%= link_to "Load Trips", user_trips_path(current_user.id), :class => "load_trips" %>
  </div>
  <div class="">
     <%= link_to "Trip Details", user_trips_path(current_user.id) %>
  </div>
  <div class="">
    <%= link_to "Add Trip", new_user_trip_path(current_user.id) %>
  </div>
  <div class="">
    <%= link_to "Filter Trips", user_trips_path(current_user.id), :class => "filter_trips" %>
  </div>
</div>

app/views/welcome/home.html.erb
<h1>Welcome to Pack-It!</h1>

<div class="links">
  <div>
    <%= link_to "Log In", login_path %>
  </div>
  <br>
  <div>
    <%= link_to "Create Account", signup_path %>
  </div>
</div>